// Generated by CoffeeScript 1.9.0
(function() {
  var moment;

  moment = require('moment');

  module.exports = {
    schedule: function(date_str, callback) {
      return setTimeout(callback, this._getTimeDiff(date_str));
    },
    _getTimeDiff: function(date_str) {
      return this._parseStrToMoment(date_str).valueOf() - moment().valueOf();
    },
    _parseStrToMoment: function(date_str) {
      var date, date_arr, hour, minute;
      date_arr = /([0-9]+):([0-9]+)/.exec(date_str);
      if (date_arr !== null) {
        hour = parseInt(date_arr[1], 10);
        minute = parseInt(date_arr[2], 10);
        if (!((0 <= hour && hour <= 23) && (0 <= minute && minute <= 59))) {
          throw new Error("invalid date");
        }
        date = moment().hours(hour).minutes(minute).seconds(0).milliseconds(0);
        if (date < moment()) {
          date.add(1, 'day');
        }
        return date;
      } else {
        return null;
      }
    }
  };

}).call(this);
