// Generated by CoffeeScript 1.9.0
(function() {
  module.exports = {
    schedule: function(date_str, callback) {
      return setTimeout(callback, this._parseDate(date_str).getTime() - (new Date).getTime());
    },
    _parseDate: function(date_str) {
      var date, date_arr, hour, minute;
      date_arr = /([0-9]+):([0-9]+)/.exec(date_str);
      if (date_arr !== null) {
        hour = parseInt(date_arr[1], 10);
        minute = parseInt(date_arr[2], 10);
        if (!((0 <= hour && hour <= 23) && (0 <= minute && minute <= 59))) {
          throw new Error("invalid date");
        }
        date = new Date;
        date.setHours(hour, minute, 0, 0);
        if (date < new Date) {
          date.setTime(date.getTime() + 24 * 60 * 60 * 1000);
        }
        return date;
      } else {
        return null;
      }
    }
  };

}).call(this);
